use super::{dialect as d, render, sort_name};
use kernel::{theory::terms, vc::vc};
use std::fmt::Write;

pub fn theory() -> String {
    let mut s = String::from(
        "-- generated by vex kernel; edit kernel/src/theory.rs instead\nnamespace kernel\n\ninductive term where\n",
    );
    for c in terms {
        write!(s, "  | {}", c.op.name()).unwrap();
        for (i, (_, t)) in c.fields.iter().enumerate() {
            write!(s, " (x{i} : {})", sort_name(*t, d::lean)).unwrap();
        }
        s.push('\n');
    }
    s.push_str("  deriving DecidableEq, Repr\n\n");
    for c in terms {
        let names = (0..c.fields.len())
            .map(|i| format!("x{i}"))
            .collect::<Vec<_>>();
        let wild = vec!["_"; c.fields.len()].join(" ");
        writeln!(
            s,
            "@[simp] def {} : term → Prop\n  | .{} {wild} => True\n  | _ => False\n",
            c.test.name(),
            c.op.name()
        )
        .unwrap();
        for (i, (p, t)) in c.fields.iter().enumerate() {
            let pats = names
                .iter()
                .enumerate()
                .map(|(j, n)| if i == j { n.as_str() } else { "_" })
                .collect::<Vec<_>>()
                .join(" ");
            writeln!(
                s,
                "@[simp] def {} : term → {}\n  | .{} {pats} => x{i}\n  | _ => {}\n",
                p.name(),
                sort_name(*t, d::lean),
                c.op.name(),
                render(&p.default(), d::lean)
            )
            .unwrap();
        }
    }
    s.push_str("end kernel\n");
    s
}

pub fn emit(v: &vc, proof: Option<&str>) -> String {
    let mut s = String::from(
        "import kernel.lean.auto\n\nopen kernel\nattribute [local instance] Classical.propDecidable\nset_option maxRecDepth 4096\nset_option maxHeartbeats 1000000\n\n",
    );
    write!(s, "theorem vc_{}", v.id).unwrap();
    let (vars, funs) = v.symbols();
    for (n, t) in vars {
        write!(s, " ({} : {})", kernel::name(&n), sort_name(t, d::lean)).unwrap();
    }
    for (n, arity) in funs {
        write!(
            s,
            " ({} : {})",
            kernel::name(&n),
            vec!["term"; arity + 1].join(" → ")
        )
        .unwrap();
    }
    for (i, h) in v.hypotheses.iter().enumerate() {
        write!(s, "\n    (h{i} : {})", render(h, d::lean)).unwrap();
    }
    write!(s, " :\n    {} :=\n", render(&v.goal, d::lean)).unwrap();
    s.push_str(proof.unwrap_or("by\n  vex_auto\n"));
    writeln!(s, "\n#vex_audit vc_{}", v.id).unwrap();
    s
}
