use super::{dialect as d, render, sort_name};
use kernel::{
    theory::{datatypes, definitions},
    vc::vc,
};
use std::fmt::Write;

pub fn theory() -> String {
    let mut s = String::from(
        "-- generated by vex kernel; edit kernel/src/theory.rs instead\nnamespace kernel\n\nmutual\n",
    );
    for (t, ctors) in datatypes {
        writeln!(s, "inductive {} where", sort_name(*t, d::lean)).unwrap();
        for c in *ctors {
            write!(s, "  | {}", c.op.name()).unwrap();
            for (i, (_, t)) in c.fields.iter().enumerate() {
                write!(s, " (x{i} : {})", sort_name(*t, d::lean)).unwrap();
            }
            s.push('\n');
        }
        s.push_str("  deriving DecidableEq, Repr\n");
    }
    s.push_str("end\n\n");
    selectors(&mut s);
    recursive(&mut s);
    s.push_str("end\n\nend kernel\n");
    s
}

fn selectors(s: &mut String) {
    for (t, ctors) in datatypes {
        let input = sort_name(*t, d::lean);
        for c in *ctors {
            let wild = vec!["_"; c.fields.len()].join(" ");
            writeln!(
                s,
                "@[simp] def {} : {input} → Prop\n  | .{} {wild} => True\n  | _ => False\n",
                c.test.name(),
                c.op.name()
            )
            .unwrap();
            for (i, (p, t)) in c.fields.iter().enumerate() {
                let pats = (0..c.fields.len())
                    .map(|j| if i == j { format!("x{i}") } else { "_".into() })
                    .collect::<Vec<_>>()
                    .join(" ");
                writeln!(
                    s,
                    "@[simp] def {} : {input} → {}\n  | .{} {pats} => x{i}\n  | _ => {}\n",
                    p.name(),
                    sort_name(*t, d::lean),
                    c.op.name(),
                    render(&p.default(), d::lean)
                )
                .unwrap();
            }
        }
    }
}

fn recursive(s: &mut String) {
    s.push_str("mutual\n");
    for def in definitions() {
        let (name, t) = &def.params[0];
        let params = def
            .params
            .iter()
            .map(|(n, t)| format!("({} : {})", kernel::name(n), sort_name(*t, d::lean)))
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(
            s,
            "@[simp] def {} {params} : {} :=\n  match {} with",
            def.op.name(),
            sort_name(def.op.output(), d::lean),
            kernel::name(name)
        )
        .unwrap();
        let (_, ctors) = datatypes.iter().find(|(s, _)| s == t).unwrap();
        for c in *ctors {
            let fields = c
                .fields
                .iter()
                .enumerate()
                .map(|(i, (_, t))| kernel::logic::expr::var(format!("f{i}"), *t))
                .collect::<Vec<_>>();
            let value = kernel::logic::expr::prim {
                op: c.op,
                args: fields.clone(),
            };
            let body = def
                .body
                .replace(&std::collections::BTreeMap::from([(name.clone(), value)]));
            let mut used = std::collections::BTreeMap::new();
            body.symbols(&mut used, &mut std::collections::BTreeMap::new());
            let pat = fields
                .iter()
                .map(|v| match v {
                    kernel::logic::expr::var { name, .. } if used.contains_key(name) => {
                        render(v, d::lean)
                    }
                    _ => "_".into(),
                })
                .collect::<Vec<_>>()
                .join(" ");
            writeln!(
                s,
                "  | .{} {pat} => {}",
                c.op.name(),
                render(&body, d::lean)
            )
            .unwrap();
        }
    }
}

pub fn emit(v: &vc, proof: Option<&str>) -> String {
    let mut s = String::from(
        "import kernel.lean.auto\n\nopen kernel\nattribute [local instance] Classical.propDecidable\nset_option maxRecDepth 4096\nset_option maxHeartbeats 1000000\n\n",
    );
    write!(s, "theorem vc_{}", v.id).unwrap();
    let (vars, funs) = v.symbols();
    for (n, t) in vars {
        write!(s, " ({} : {})", kernel::name(&n), sort_name(t, d::lean)).unwrap();
    }
    for (n, arity) in funs {
        write!(
            s,
            " ({} : {})",
            kernel::name(&n),
            vec!["term"; arity + 1].join(" → ")
        )
        .unwrap();
    }
    for (i, h) in v.hypotheses.iter().enumerate() {
        write!(s, "\n    (h{i} : {})", render(h, d::lean)).unwrap();
    }
    write!(s, " :\n    {} :=\n", render(&v.goal, d::lean)).unwrap();
    s.push_str(proof.unwrap_or("by\n  vex_auto\n"));
    writeln!(s, "\n#vex_audit vc_{}", v.id).unwrap();
    s
}
