-- generated by vex kernel; edit kernel/src/theory.rs instead
namespace kernel

mutual
inductive term where
  | int (x0 : Int)
  | atom (x0 : Int)
  | nil
  | cons (x0 : term) (x1 : term)
  | tuple (x0 : seq)
  deriving DecidableEq, Repr
inductive seq where
  | empty
  | push (x0 : term) (x1 : seq)
  deriving DecidableEq, Repr
end

@[simp] def is_int : term → Prop
  | .int _ => True
  | _ => False

@[simp] def ival : term → Int
  | .int x0 => x0
  | _ => (0 : Int)

@[simp] def is_atom : term → Prop
  | .atom _ => True
  | _ => False

@[simp] def aval : term → Int
  | .atom x0 => x0
  | _ => (0 : Int)

@[simp] def is_nil : term → Prop
  | .nil  => True
  | _ => False

@[simp] def is_cons : term → Prop
  | .cons _ _ => True
  | _ => False

@[simp] def head : term → term
  | .cons x0 _ => x0
  | _ => term.nil

@[simp] def tail : term → term
  | .cons _ x1 => x1
  | _ => term.nil

@[simp] def is_tuple : term → Prop
  | .tuple _ => True
  | _ => False

@[simp] def items : term → seq
  | .tuple x0 => x0
  | _ => seq.empty

@[simp] def is_empty : seq → Prop
  | .empty  => True
  | _ => False

@[simp] def is_push : seq → Prop
  | .push _ _ => True
  | _ => False

@[simp] def first : seq → term
  | .push x0 _ => x0
  | _ => term.nil

@[simp] def rest : seq → seq
  | .push _ x1 => x1
  | _ => seq.empty

mutual
@[simp] def len (v7873 : seq) : Int :=
  match v7873 with
  | .empty  => (0 : Int)
  | .push _ v6631 => ((1 : Int) + (kernel.len v6631))
@[simp] def nth (v7873 : seq) (v69 : Int) : term :=
  match v7873 with
  | .empty  => term.nil
  | .push v6630 v6631 => (if ((0 : Int) ≤ v69) then (if (v69 = (0 : Int)) then v6630 else (kernel.nth v6631 (v69 - (1 : Int)))) else term.nil)
@[simp] def size (v78 : term) : Int :=
  match v78 with
  | .int _ => (1 : Int)
  | .atom _ => (1 : Int)
  | .nil  => (1 : Int)
  | .cons v6630 v6631 => ((1 : Int) + ((kernel.size v6630) + (kernel.size v6631)))
  | .tuple v6630 => ((1 : Int) + (kernel.mass v6630))
@[simp] def mass (v7873 : seq) : Int :=
  match v7873 with
  | .empty  => (0 : Int)
  | .push v6630 v6631 => ((kernel.size v6630) + (kernel.mass v6631))
end

end kernel
