-- generated by vex kernel; edit kernel/src/theory.rs instead
namespace kernel

inductive term where
  | int (x0 : Int)
  | atom (x0 : Int)
  | nil
  | cons (x0 : term) (x1 : term)
  | tuple (x0 : term)
  deriving DecidableEq, Repr

@[simp] def is_int : term → Prop
  | .int _ => True
  | _ => False

@[simp] def ival : term → Int
  | .int x0 => x0
  | _ => (0 : Int)

@[simp] def is_atom : term → Prop
  | .atom _ => True
  | _ => False

@[simp] def aval : term → Int
  | .atom x0 => x0
  | _ => (0 : Int)

@[simp] def is_nil : term → Prop
  | .nil  => True
  | _ => False

@[simp] def is_cons : term → Prop
  | .cons _ _ => True
  | _ => False

@[simp] def head : term → term
  | .cons x0 _ => x0
  | _ => term.nil

@[simp] def tail : term → term
  | .cons _ x1 => x1
  | _ => term.nil

@[simp] def is_tuple : term → Prop
  | .tuple _ => True
  | _ => False

@[simp] def items : term → term
  | .tuple x0 => x0
  | _ => term.nil

end kernel
